
# Production Application Configuration
application:
  name: DevOpsSimulator
  version: 1.0.0
  environment: production
  
server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true
  
logging:
  level: INFO
  format: json
  output: /var/log/app.log
  
database:
  host: prod-db.example.com
  port: 5432
  name: devops_prod
  
features:
  auto_scaling: true
  load_balancer: enabled
  backup_enabled: true

# Development Application Configuration

development:
  enabled: false
  host: localhost
  port: 3000
  ssl_enabled: false
  hot_reload: false
  logging_level: DEBUG
  logging_format: pretty
  logging_output: console
  show_stack_trace: false
  database_host: localhost
  database_name: devops_dev
  experimental_features: false
  mock_external_apis: false
  debug_mode: false
  cors_enabled: false
  
notifications:
  slack_webhook: "https://hooks.slack.com/services/XXX"
  discord_webhook: "https://discord.com/api/webhooks/YYY"
  email_alerts: false

