# DevOps Simulator Application Configuration

application:
  name: DevOpsSimulator
  version: 3.0.0-experimental
  environment: production
  experimental_mode: true

server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true
  multi_port: [8080, 9000, 9001, 9002] # combined production & experimental ports

logging:
  level: TRACE
  format: structured
  output: /var/log/app.log
  ai_analysis: enabled

database:
  host: prod-db.example.com
  port: 5432
  name: devops_prod
  distributed: true

features:
  auto_scaling: true
  load_balancer: enabled
  backup_enabled: true

  # Experimental features (commented out for production)
  # auto_scaling: advanced
  # load_balancer: ai-optimized
  # chaos_engineering: enabled

development:
  enabled: true
  host: localhost
  port: 3000
  ssl_enabled: false
  hot_reload: true
  logging_level: DEBUG
  logging_format: pretty
  logging_output: console
  show_stack_trace: true
  database_host: localhost
  database_name: devops_dev
  experimental_features: true
  mock_external_apis: true
  debug_mode: true
  cors_enabled: true

ai_features:
  predictive_scaling: true
  anomaly_detection: true
  auto_optimization: true
  model_version: "v2.1.0"

cloud_providers:
  - aws
  - azure
  - gcp
  - digitalocean

security:
  zero_trust: enabled
  encryption: AES-256
  audit_logging: comprehensive

notifications:
  slack_webhook: "https://hooks.slack.com/services/XXX"
  discord_webhook: "https://discord.com/api/webhooks/YYY"
  email_alerts: false
